services:
  web:
    build:
      context: .
    ports:
      - '8000:8000'
    restart: always
    container_name: 'telegram_price-bot'
    volumes:
      - .:/app
    environment:
      - .env
    command: >
      sh -c "python main.py"
    depends_on:
#      - database
      - selenium
#      - redis

  selenium:
    image: 'selenium/standalone-chrome'
    ports:
      - '4444:4444'
      - '7900:7900'
    restart: always
    shm_size: '512m'
    container_name: 'selenium_grid'

#  database:
#    image: postgres:16.2-alpine
#    environment:
#      - .env
#
#  redis:
#    image: redis:7.2.4-alpine
#    restart: always
#    hostname: redis
#    command: redis-server
#    ports:
#      - '6379:6379'
#
#  worker:
#    build:
#      context: .
#    hostname: worker
#    entrypoint: celery
#    command: -A config worker --loglevel=info
#    #    command: sh -c "python -m celery -A config worker"
#    #    command: -A config worker -l INFO
#    #    command: [ '--workdir=./src', '-A', 'config', 'worker' ]
#    volumes:
#      - .:/code
#    links:
#      - redis
#    depends_on:
#      - web
#      - redis
#
#  flower:
#    build:
#      context: .
#    hostname: flower
#    entrypoint: celery
#    command: -A config flower
#    volumes:
#      - .:/code
#    depends_on:
#      - redis
#    ports:
#      - "5555:5555"